In [1]:
import numpy as np
import pandas as pd
import json

In [2]:
f1=pd.read_json('access_to_elec_rural.json')

f1.to_csv('file1.csv')

f1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [3]:
#f1.drop([f1.index[0]],axis=0,inplace=True)

f1.drop(0,axis=0,inplace=True)
f1

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [4]:
f1.columns=f1.iloc[0]
f1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [5]:





f1.drop(1,axis=0,inplace=True)
f1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,,,3.81506657600403,,,7.33344507217407,,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [6]:

f1.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,NaN,
2,4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,NaN,
3,5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,NaN,
4,6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,,,3.81506657600403,,,7.33344507217407,,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,NaN,
262,264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,NaN,
263,265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,NaN,
264,266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,NaN,
265,267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,NaN,

In [7]:



f1.isnull().sum()

1
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960.0            266
                 ...
2018                0
2019                0
2020                0
2021.0            266
                    0
Length: 67, dtype: int64

In [8]:
f1.dtypes

1
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960.0            float64
                   ...
2018               object
2019               object
2020               object
2021.0            float64
                   object
Length: 67, dtype: object

In [9]:
f1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          0 non-null      float64
 5   1961.0          0 non-null      float64
 6   1962.0          0 non-null      float64
 7   1963.0          0 non-null      float64
 8   1964.0          0 non-null      float64
 9   1965.0          0 non-null      float64
 10  1966.0          0 non-null      float64
 11  1967.0          0 non-null      float64
 12  1968.0          0 non-null      float64
 13  1969.0          0 non-null      float64
 14  1970.0          0 non-null      float64
 15  1971.0          0 non-null      float64
 16  1972.0          0 non-null      float64
 17  1973.0          0 non-null      float64
 18  1974.0          0 non-null      float64
 19  1975.0          0 non-null      float64
 20  1976.0          0 non-null      float64
 21  1977.0          0 non-null      float64
 22  1978.0          0 non-null      float64
 23  1979.0          0 non-null      float64
 24  1980.0          0 non-null      float64
 25  1981.0          0 non-null      float64
 26  1982.0          0 non-null      float64
 27  1983.0          0 non-null      float64
 28  1984.0          0 non-null      float64
 29  1985.0          0 non-null      float64
 30  1986.0          0 non-null      float64
 31  1987.0          0 non-null      float64
 32  1988.0          0 non-null      float64
 33  1989.0          0 non-null      float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [10]:


f1.fillna(0, inplace=True)
f1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0.0,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0.0,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0.0,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0.0,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0.0,

In [12]:
#df["bmi"] = pd.to_numeric(df["bmi"], errors = "coerce")

### dic = {}
for i in f1.columns[34:67]:
    dic[i] = int(i)
    
f1["i"] = pd.to_numeric(f1["i"], errors = "coerce")

# rename all columns' name

In [13]:
#for i in f1.columns[4:66]:
    #f1.rename({str(i):'_'+str(i)}, axis=1, inplace=True)
#f1.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,__2013,__2014,__2015,__2016,__2017,__2018,__2019,__2020,2021.0,_
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,

In [13]:

f1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    float64
 5   1961.0          266 non-null    float64
 6   1962.0          266 non-null    float64
 7   1963.0          266 non-null    float64
 8   1964.0          266 non-null    float64
 9   1965.0          266 non-null    float64
 10  1966.0          266 non-null    float64
 11  1967.0          266 non-null    float64
 12  1968.0          266 non-null    float64
 13  1969.0          266 non-null    float64
 14  1970.0          266 non-null    float64
 15  1971.0          266 non-null    float64
 16  1972.0          266 non-null    float64
 17  1973.0          266 non-null    float64
 18  1974.0          266 non-null    float64
 19  1975.0          266 non-null    float64
 20  1976.0          266 non-null    float64
 21  1977.0          266 non-null    float64
 22  1978.0          266 non-null    float64
 23  1979.0          266 non-null    float64
 24  1980.0          266 non-null    float64
 25  1981.0          266 non-null    float64
 26  1982.0          266 non-null    float64
 27  1983.0          266 non-null    float64
 28  1984.0          266 non-null    float64
 29  1985.0          266 non-null    float64
 30  1986.0          266 non-null    float64
 31  1987.0          266 non-null    float64
 32  1988.0          266 non-null    float64
 33  1989.0          266 non-null    float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [15]:
#Changing the column name

dic = {}
for i in f1.columns[4:67]:
    dic[i] = str(i)

    
f1.rename(columns = dic, inplace = True)
f1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,__2013,__2014,__2015,__2016,__2017,__2018,__2019,__2020,2021.0,_
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0.0,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0.0,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0.0,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0.0,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0.0,

In [88]:
f1.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)

In [89]:
f1

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,__2013,__2014,__2015,__2016,__2017,__2018,__2019,__2020,2021.0,_
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0.0,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0.0,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0.0,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0.0,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0.0,

In [15]:
f1.columns[-1]

''

In [16]:
f1.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,

In [17]:
f1.ffill(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6635016376268,17.6339864137494,16.4646807920084,24.5314360859943,25.3451111513968,27.449907671217,29.641760454315,30.4049349446892,0.0,
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.5661354064941,86.5005111694336,64.573356628418,97.0993576049805,97.0919723510742,95.5861740112305,97.0756301879883,97.0667114257813,0.0,
5,Africa Western and Central,AFW,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2940777859074,22.5498249303203,22.7805919695114,27.3802199490347,,,,25.4667951085453,0.0,
6,Angola,AGO,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,,,3.81506657600403,,,7.33344507217407,,,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.5100021362305,99.5,99.7900009155273,99.8000030517578,99.6999969482422,,100,,0.0,
264,"Yemen, Rep.",YEM,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,64.033332824707,50.624942779541,53.5731163024902,55.6699600219727,71.4414443969727,,60.6768035888672,61.9411163330078,0.0,
265,South Africa,ZAF,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,80.7377853393555,82.2866439819336,80.1979446411133,75.7492752075195,76.7389831542969,77.1684951782227,77.6118240356445,75.2648544311523,0.0,
266,Zambia,ZMB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,8.13744926452637,4.1797251701355,4.69756984710693,9.96357250213623,13.9976968765259,12.4664363861084,14.2673807144165,14.0108251571655,0.0,
267,Zimbabwe,ZWE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6982822418213,7.69181156158447,10.9493141174316,22.0870532989502,24.5310878753662,26.6171207427979,28.4048767089844,37.0602493286133,0.0,

In [18]:
f1.to_csv('Downloads/elec_rural.csv')

In [35]:
f2=pd.read_json('access_total_elec.json')
f2.to_csv('file2.csv')
f2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [36]:
f2.drop(0,axis=0,inplace=True)
f2

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [37]:



f2.columns=f2.iloc[0]
f2

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [38]:
f2.drop(1, axis = 0, inplace = True)
f2

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [22]:

#
f2.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
2,4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
3,5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
4,6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
262,264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
263,265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
264,266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
265,267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

In [23]:

f2.fillna(0, inplace=True)
f2

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,0.0,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,0.0,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,0.0,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,0.0,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,0.0,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,0.0,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,0.0,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,0.0,

# rename all columns' name

In [39]:
 for i in f2.columns[4:]:
    f2.rename({str(i):'_'+str(i)}, axis=1, inplace=True)


f2.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,2021.0,_
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,NaN,

In [86]:
f2.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)

In [87]:
f2

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,1965.0,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,_2021,_
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,NaN,
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,NaN,
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,NaN,
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.75,99.6800003051758,99.8600006103516,99.8000030517578,99.8000030517578,,100,,NaN,
264,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5999984741211,66.0999984741211,67.3109283447266,68.859504699707,79.1999969482422,62,72.7510757446289,73.757926940918,NaN,
265,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.1999969482422,85.9000015258789,85.3000030517578,83.9000015258789,84.4000015258789,84.6999969482422,85,84.3855361938477,NaN,
266,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,29.8862724304199,27.8999996185303,31.1000003814697,35.4254531860352,40.2999992370605,40.3178901672363,43,44.5244750976563,NaN,
267,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,40.4983749389648,32.2999992370605,33.7000007629395,42.5617294311523,44.1786346435547,45.5726470947266,46.7814750671387,52.7476692199707,NaN,

# #dic = {}
#for i in f2.columns[4:67]:
    #dic[i] = str(i)

    
#f2.rename(columns = dic, inplace = True)
#f2


rename all columns' name¶

In [26]:
f2.columns[-1]

''

In [27]:
f2.drop('', axis = 1, inplace = True)

In [30]:
f2.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960.0,_1961.0,_1962.0,_1963.0,_1964.0,_1965.0,...,_2012,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,_2021.0
2,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,100,0.0
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,31.8443844038242,31.794159992766,32.001026781227,33.8719104646129,38.8801732244203,40.261357595893,43.061876950924,44.2708604789338,45.8034852293868,0.0
4,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,69.0999984741211,68.2906494140625,89.5,71.5,97.6999969482422,97.6999969482422,96.6161346435547,97.6999969482422,97.6999969482422,0.0
5,Africa Western and Central,AFW,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,44.1679733535959,47.0483161636866,47.5993227916858,46.7662943639277,50.9534866843105,48.8611912179155,51.2597116422012,51.2901929896648,52.1116010037919,0.0
6,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,37.1313209533691,38.2780303955078,32,42,41.8131294250488,43.0132598876953,45.2900009155273,45.6427993774414,46.8906097412109,0.0

In [31]:
f2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 66 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   _1960.0         266 non-null    float64
 5   _1961.0         266 non-null    float64
 6   _1962.0         266 non-null    float64
 7   _1963.0         266 non-null    float64
 8   _1964.0         266 non-null    float64
 9   _1965.0         266 non-null    float64
 10  _1966.0         266 non-null    float64
 11  _1967.0         266 non-null    float64
 12  _1968.0         266 non-null    float64
 13  _1969.0         266 non-null    float64
 14  _1970.0         266 non-null    float64
 15  _1971.0         266 non-null    float64
 16  _1972.0         266 non-null    float64
 17  _1973.0         266 non-null    float64
 18  _1974.0         266 non-null    float64
 19  _1975.0         266 non-null    float64
 20  _1976.0         266 non-null    float64
 21  _1977.0         266 non-null    float64
 22  _1978.0         266 non-null    float64
 23  _1979.0         266 non-null    float64
 24  _1980.0         266 non-null    float64
 25  _1981.0         266 non-null    float64
 26  _1982.0         266 non-null    float64
 27  _1983.0         266 non-null    float64
 28  _1984.0         266 non-null    float64
 29  _1985.0         266 non-null    float64
 30  _1986.0         266 non-null    float64
 31  _1987.0         266 non-null    float64
 32  _1988.0         266 non-null    float64
 33  _1989.0         266 non-null    float64
 34  _1990           266 non-null    object
 35  _1991           266 non-null    object
 36  _1992           266 non-null    object
 37  _1993           266 non-null    object
 38  _1994           266 non-null    object
 39  _1995           266 non-null    object
 40  _1996           266 non-null    object
 41  _1997           266 non-null    object
 42  _1998           266 non-null    object
 43  _1999           266 non-null    object
 44  _2000           266 non-null    object
 45  _2001           266 non-null    object
 46  _2002           266 non-null    object
 47  _2003           266 non-null    object
 48  _2004           266 non-null    object
 49  _2005           266 non-null    object
 50  _2006           266 non-null    object
 51  _2007           266 non-null    object
 52  _2008           266 non-null    object
 53  _2009           266 non-null    object
 54  _2010           266 non-null    object
 55  _2011           266 non-null    object
 56  _2012           266 non-null    object
 57  _2013           266 non-null    object
 58  _2014           266 non-null    object
 59  _2015           266 non-null    object
 60  _2016           266 non-null    object
 61  _2017           266 non-null    object
 62  _2018           266 non-null    object
 63  _2019           266 non-null    object
 64  _2020           266 non-null    object
 65  _2021.0         266 non-null    float64
dtypes: float64(31), object(35)
memory usage: 137.3+ KB

In [32]:
f2.to_csv('Downloads/access_total.csv')

In [40]:



f3=pd.read_json('access_to_elec_urban.json')
f3.to_csv('file3.csv')
f3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [41]:

f3.drop(0,axis=0,inplace=True)
f3

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [43]:
f3.columns=f3.iloc[0]
f3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [44]:
f3.drop(1, axis = 0, inplace = True)
f3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [46]:
f3.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
0,2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,100,100,100,100,100,100,100,100,NaN,
1,3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,NaN,
2,4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,NaN,
3,5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,NaN,
4,6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,NaN,
262,264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,NaN,
263,265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,NaN,
264,266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,NaN,
265,267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,NaN,

In [47]:
f3.fillna(0, inplace=True)
f3

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013,2014,2015,2016,2017,2018,2019,2020,2021.0,
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0.0,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0.0,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0.0,
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0.0,
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0.0,
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0.0,
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0.0,
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0.0,

# rename all columns' name

In [52]:
for i in f3.columns[4:]:
    f3.rename({str(i):'_'+str(i)}, axis=1, inplace=True)


f3.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960.0,_1961.0,_1962.0,_1963.0,_1964.0,_1965.0,...,__2013,__2014,__2015,__2016,__2017,__2018,__2019,__2020,_2021.0,__
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,0.0,
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0.0,
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0.0,
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0.0,
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0.0,

In [90]:
f3.rename({1960.0:'_1960',1961.0:'_1961',1962.0:'_1962',1963.0:'_1963',1964.0:'_1964',2021.0:'_2021'},axis=1,inplace=True)

In [91]:
f3

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960.0,_1961.0,_1962.0,_1963.0,_1964.0,_1965.0,...,__2012,__2013,__2014,__2015,__2016,__2017,__2018,__2019,__2020,_2021.0
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,100,0.0
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,66.9452771502516,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0.0
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,95,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0.0
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,78.6990973259095,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0.0
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,70.4634704589844,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.8899993896484,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0.0
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.4911727905273,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0.0
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,87.5486831665039,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0.0
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.1433067321777,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0.0
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.4305267333984,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0.0

In [48]:
f3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    float64
 5   1961.0          266 non-null    float64
 6   1962.0          266 non-null    float64
 7   1963.0          266 non-null    float64
 8   1964.0          266 non-null    float64
 9   1965.0          266 non-null    float64
 10  1966.0          266 non-null    float64
 11  1967.0          266 non-null    float64
 12  1968.0          266 non-null    float64
 13  1969.0          266 non-null    float64
 14  1970.0          266 non-null    float64
 15  1971.0          266 non-null    float64
 16  1972.0          266 non-null    float64
 17  1973.0          266 non-null    float64
 18  1974.0          266 non-null    float64
 19  1975.0          266 non-null    float64
 20  1976.0          266 non-null    float64
 21  1977.0          266 non-null    float64
 22  1978.0          266 non-null    float64
 23  1979.0          266 non-null    float64
 24  1980.0          266 non-null    float64
 25  1981.0          266 non-null    float64
 26  1982.0          266 non-null    float64
 27  1983.0          266 non-null    float64
 28  1984.0          266 non-null    float64
 29  1985.0          266 non-null    float64
 30  1986.0          266 non-null    float64
 31  1987.0          266 non-null    float64
 32  1988.0          266 non-null    float64
 33  1989.0          266 non-null    float64
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016            266 non-null    object
 61  2017            266 non-null    object
 62  2018            266 non-null    object
 63  2019            266 non-null    object
 64  2020            266 non-null    object
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(31), object(36)
memory usage: 139.4+ KB

In [54]:
f3.columns[-1]

'__'

In [56]:
f3.drop('__', axis = 1, inplace = True)

In [57]:
f3

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960.0,_1961.0,_1962.0,_1963.0,_1964.0,_1965.0,...,__2012,__2013,__2014,__2015,__2016,__2017,__2018,__2019,__2020,_2021.0
2,Aruba,ABW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,100,100,100,100,100,100,100,100,100,0.0
3,Africa Eastern and Southern,AFE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,66.9452771502516,67.1122062807782,66.2834263727233,67.0802345160891,69.1322924194883,70.9285671571016,71.8661360685467,73.3328420364472,73.9429490467264,0.0
4,Afghanistan,AFG,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,95,92.2590484619141,98.6999969482422,92.5,99.5,99.5,99.6260223388672,99.5,99.5,0.0
5,Africa Western and Central,AFW,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,78.6990973259095,78.8486136952441,79.52923504769,78.2478757011491,81.5715174202803,,,,83.220064935553,0.0
6,Angola,AGO,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,70.4634704589844,68.662223815918,51,64,67.9733963012695,69.4111709594727,65.2699966430664,72.2771835327148,73.7089157104492,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.8899993896484,100,99.8600006103516,99.9300003051758,99.8000030517578,100,,99.9000015258789,,0.0
264,"Yemen, Rep.",YEM,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,99.4911727905273,98.5,95.9199981689453,93.0756988525391,92.9348754882813,92.9834136962891,,93.0709533691406,93.1134567260742,0.0
265,South Africa,ZAF,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,87.5486831665039,87.7326202392578,87.9051208496094,88.0680847167969,88.2234115600586,88.3730239868164,88.5188140869141,88.6627044677734,88.806266784668,0.0
266,Zambia,ZMB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,60.1433067321777,61.3586006164551,61.5,67.6999969482422,69.9614105224609,75.1999969482422,76.4618759155273,79.4621047973633,82.3826217651367,0.0
267,Zimbabwe,ZWE,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,0.0,0.0,0.0,0.0,0.0,0.0,...,85.4305267333984,85.4591522216797,83.4000015258789,81.1999969482422,85.4839935302734,85.4782867431641,85.4687652587891,85.4573364257813,85.7154769897461,0.0

# save the csv file after cleaning (make sure give correct path for saving the file as per your choice)

In [ ]:
f3.to_csv('c:/access_to_elec_urban.csv', index=False)

In [62]:
f4=pd.read_json('elec_power_trans.json')
f4.to_csv('file4.csv')

f4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [63]:

f4.drop(0,axis=0,inplace=True)
f4

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [65]:
f4.columns=f4.iloc[0]
f4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [66]:
f4.drop(1, axis = 0, inplace = True)
f4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [67]:
f4.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,10.3931823810978,10.5947656106552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,18.2006600449596,17.9031474055171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,11.2706913339825,11.2658227848101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,13.4712643678161,15.0478292862399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
262,264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,25.7616750970474,25.7651059377452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
263,265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,8.48684002654112,8.39376119869644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
264,266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,8.56390977443609,14.9598671464157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
265,267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,...,17.7847439916405,16.4372631158987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [68]:
f4.fillna(0, inplace=True)
f4

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

# rename all columns' name¶

In [71]:
for i in f4.columns[4:]:
    f4.rename({str(i):'_'+str(i)}, axis=1, inplace=True)
f4.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,__1960,__1961,__1962,__1963,__1964,__1965,...,__2013,__2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,

In [69]:
f4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015.0          266 non-null    float64
 60  2016.0          266 non-null    float64
 61  2017.0          266 non-null    float64
 62  2018.0          266 non-null    float64
 63  2019.0          266 non-null    float64
 64  2020.0          266 non-null    float64
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(7), object(60)
memory usage: 139.4+ KB

# fill values from 2016 to 2021

In [72]:
 for i,v in enumerate(f4.columns[60:]):
     f4[v] = f4[f4.columns[56+i:60+i]].mean(axis=1)
f4

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9176\1540340825.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  f4[v] = f4[f4.columns[56+i:60+i]].mean(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,__1960,__1961,__1962,__1963,__1964,__1965,...,__2013,__2014,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,10.3931823810978,10.5947656106552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Africa Western and Central,AFW,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,18.2006600449596,17.9031474055171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Angola,AGO,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,11.2706913339825,11.2658227848101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,13.4712643678161,15.0478292862399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,25.7616750970474,25.7651059377452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.48684002654112,8.39376119869644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,8.56390977443609,14.9598671464157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electric power transmission and distribution l...,EG.ELC.LOSS.ZS,,,,,,,...,17.7847439916405,16.4372631158987,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# save the csv file after cleaning (make sure give correct path for saving the file as per your choice)¶

In [ ]:
f4.to_csv('c:/elec_power_trans.csv', index=False)

In [74]:
f5=pd.read_json('elec_production_nuclear_resources.json')
f5.to_csv('file5.csv')
f5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [75]:
f5.drop(0,axis=0,inplace=True)
f5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [76]:
f5.columns=f5.iloc[0]
f5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [79]:
f5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [81]:
f5.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
2,4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
4,6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
262,264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
263,265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
264,266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

# rename all columns' name

In [93]:
f5.rename({2016.0:'_2016',2017.0:'_2017',2018.0:'_2018',2019.0:'_2019',2020.0:'_2020',2021.0:'_2021'},axis=1,inplace=True)

In [94]:
f5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,_2016,_2017,_2018,_2019,_2020,_2021,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,NaN,NaN,NaN,NaN,NaN,NaN,

In [92]:
f5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(6), object(61)
memory usage: 139.4+ KB

In [95]:
f5.fillna(0, inplace=True)
f5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,_2016,_2017,_2018,_2019,_2020,_2021,
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,,0.0,0.0,0.0,0.0,0.0,0.0,

In [97]:
f5.drop('', axis = 1, inplace = True)

In [98]:
f5

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,_2016,_2017,_2018,_2019,_2020,_2021
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,,0.0,0.0,0.0,0.0,0.0,0.0
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.21286201581089,3.73257405151658,3.58003778041762,,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,,0.0,0.0,0.0,0.0,0.0,0.0
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,0.0,0.0,0.0,0.0,0.0,0.0
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,0.0,0.0,0.0,0.0,0.0,0.0
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,0.0,0.0,0.0,0.0,0.0,0.0
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,4.68944306488881,5.5712660747575,5.52929999879746,,0.0,0.0,0.0,0.0,0.0,0.0
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,0.0,0.0,0.0,0.0,0.0,0.0
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,0.0,0.0,0.0,0.0,0.0,0.0

# fill values from 2016 to 2021

In [99]:
for i,v in enumerate(f5.columns[60:]):
    f5[v] = f5[f5.columns[56+i:60+i]].mean(axis=1)
f5

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9176\2887506455.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  f5[v] = f5[f5.columns[56+i:60+i]].mean(axis=1)

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,_2016,_2017,_2018,_2019,_2020,_2021
2,Aruba,ABW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,3.21286201581089,3.73257405151658,3.58003778041762,,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Western and Central,AFW,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,NaN,NaN,NaN,NaN,NaN,NaN
6,Angola,AGO,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,4.68944306488881,5.5712660747575,5.52929999879746,,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from nuclear sources (%...,EG.ELC.NUCL.ZS,,,,,,,...,0,0,0,,NaN,NaN,NaN,NaN,NaN,NaN

# save the csv file after cleaning (make sure give correct path for saving the file as per your choice)

In [ ]:
f5.to_csv('c:/elec_production_nuclear_resources.csv', index=False)

In [54]:
f6=pd.read_json('elec_produc_oil_resources.json')
f6.to_csv('file6.csv')

f6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

# DATA information

In [55]:
f6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 67 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       268 non-null    object
 1   1       268 non-null    object
 2   2       268 non-null    object
 3   3       268 non-null    object
 4   4       268 non-null    object
 5   5       268 non-null    object
 6   6       268 non-null    object
 7   7       268 non-null    object
 8   8       268 non-null    object
 9   9       268 non-null    object
 10  10      268 non-null    object
 11  11      268 non-null    object
 12  12      268 non-null    object
 13  13      268 non-null    object
 14  14      268 non-null    object
 15  15      268 non-null    object
 16  16      268 non-null    object
 17  17      268 non-null    object
 18  18      268 non-null    object
 19  19      268 non-null    object
 20  20      268 non-null    object
 21  21      268 non-null    object
 22  22      268 non-null    object
 23  23      268 non-null    object
 24  24      268 non-null    object
 25  25      268 non-null    object
 26  26      268 non-null    object
 27  27      268 non-null    object
 28  28      268 non-null    object
 29  29      268 non-null    object
 30  30      268 non-null    object
 31  31      268 non-null    object
 32  32      268 non-null    object
 33  33      268 non-null    object
 34  34      268 non-null    object
 35  35      268 non-null    object
 36  36      268 non-null    object
 37  37      268 non-null    object
 38  38      268 non-null    object
 39  39      268 non-null    object
 40  40      268 non-null    object
 41  41      268 non-null    object
 42  42      268 non-null    object
 43  43      268 non-null    object
 44  44      268 non-null    object
 45  45      268 non-null    object
 46  46      268 non-null    object
 47  47      268 non-null    object
 48  48      268 non-null    object
 49  49      268 non-null    object
 50  50      268 non-null    object
 51  51      268 non-null    object
 52  52      268 non-null    object
 53  53      268 non-null    object
 54  54      268 non-null    object
 55  55      268 non-null    object
 56  56      268 non-null    object
 57  57      268 non-null    object
 58  58      268 non-null    object
 59  59      268 non-null    object
 60  60      1 non-null      float64
 61  61      1 non-null      float64
 62  62      1 non-null      float64
 63  63      1 non-null      float64
 64  64      1 non-null      float64
 65  65      1 non-null      float64
 66  66      268 non-null    object
dtypes: float64(6), object(61)
memory usage: 140.4+ KB

In [56]:
f6.drop(0,axis=0,inplace=True)
f6

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [57]:
f6.columns=f6.iloc[0]
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [58]:
f6.drop(1,axis=0,inplace=True)

In [59]:
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [41]:
f6.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
2,3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
3,4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
4,5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
263,264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
264,265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
265,266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
266,267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [43]:
f6.fillna(0, inplace=True)
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,

In [60]:
f6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            266 non-null    object
 5   1961            266 non-null    object
 6   1962            266 non-null    object
 7   1963            266 non-null    object
 8   1964            266 non-null    object
 9   1965            266 non-null    object
 10  1966            266 non-null    object
 11  1967            266 non-null    object
 12  1968            266 non-null    object
 13  1969            266 non-null    object
 14  1970            266 non-null    object
 15  1971            266 non-null    object
 16  1972            266 non-null    object
 17  1973            266 non-null    object
 18  1974            266 non-null    object
 19  1975            266 non-null    object
 20  1976            266 non-null    object
 21  1977            266 non-null    object
 22  1978            266 non-null    object
 23  1979            266 non-null    object
 24  1980            266 non-null    object
 25  1981            266 non-null    object
 26  1982            266 non-null    object
 27  1983            266 non-null    object
 28  1984            266 non-null    object
 29  1985            266 non-null    object
 30  1986            266 non-null    object
 31  1987            266 non-null    object
 32  1988            266 non-null    object
 33  1989            266 non-null    object
 34  1990            266 non-null    object
 35  1991            266 non-null    object
 36  1992            266 non-null    object
 37  1993            266 non-null    object
 38  1994            266 non-null    object
 39  1995            266 non-null    object
 40  1996            266 non-null    object
 41  1997            266 non-null    object
 42  1998            266 non-null    object
 43  1999            266 non-null    object
 44  2000            266 non-null    object
 45  2001            266 non-null    object
 46  2002            266 non-null    object
 47  2003            266 non-null    object
 48  2004            266 non-null    object
 49  2005            266 non-null    object
 50  2006            266 non-null    object
 51  2007            266 non-null    object
 52  2008            266 non-null    object
 53  2009            266 non-null    object
 54  2010            266 non-null    object
 55  2011            266 non-null    object
 56  2012            266 non-null    object
 57  2013            266 non-null    object
 58  2014            266 non-null    object
 59  2015            266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(6), object(61)
memory usage: 139.4+ KB

In [53]:
f6.drop(1,axis=0,inplace=True)
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,____1960,____1961,____1962,____1963,____1964,____1965,...,____2013,____2014,____2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,0.0,0.0,0.0,0.0,0.0,0.0,

# rename all columns' name

In [61]:
#
for i in f6.columns[4:66]:
    f6.rename({str(i):'_'+str(i)}, axis=1, inplace=True)
f6.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,

In [62]:
f6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   _1960           266 non-null    object
 5   _1961           266 non-null    object
 6   _1962           266 non-null    object
 7   _1963           266 non-null    object
 8   _1964           266 non-null    object
 9   _1965           266 non-null    object
 10  _1966           266 non-null    object
 11  _1967           266 non-null    object
 12  _1968           266 non-null    object
 13  _1969           266 non-null    object
 14  _1970           266 non-null    object
 15  _1971           266 non-null    object
 16  _1972           266 non-null    object
 17  _1973           266 non-null    object
 18  _1974           266 non-null    object
 19  _1975           266 non-null    object
 20  _1976           266 non-null    object
 21  _1977           266 non-null    object
 22  _1978           266 non-null    object
 23  _1979           266 non-null    object
 24  _1980           266 non-null    object
 25  _1981           266 non-null    object
 26  _1982           266 non-null    object
 27  _1983           266 non-null    object
 28  _1984           266 non-null    object
 29  _1985           266 non-null    object
 30  _1986           266 non-null    object
 31  _1987           266 non-null    object
 32  _1988           266 non-null    object
 33  _1989           266 non-null    object
 34  _1990           266 non-null    object
 35  _1991           266 non-null    object
 36  _1992           266 non-null    object
 37  _1993           266 non-null    object
 38  _1994           266 non-null    object
 39  _1995           266 non-null    object
 40  _1996           266 non-null    object
 41  _1997           266 non-null    object
 42  _1998           266 non-null    object
 43  _1999           266 non-null    object
 44  _2000           266 non-null    object
 45  _2001           266 non-null    object
 46  _2002           266 non-null    object
 47  _2003           266 non-null    object
 48  _2004           266 non-null    object
 49  _2005           266 non-null    object
 50  _2006           266 non-null    object
 51  _2007           266 non-null    object
 52  _2008           266 non-null    object
 53  _2009           266 non-null    object
 54  _2010           266 non-null    object
 55  _2011           266 non-null    object
 56  _2012           266 non-null    object
 57  _2013           266 non-null    object
 58  _2014           266 non-null    object
 59  _2015           266 non-null    object
 60  2016.0          0 non-null      float64
 61  2017.0          0 non-null      float64
 62  2018.0          0 non-null      float64
 63  2019.0          0 non-null      float64
 64  2020.0          0 non-null      float64
 65  2021.0          0 non-null      float64
 66                  266 non-null    object
dtypes: float64(6), object(61)
memory usage: 139.4+ KB

In [63]:
f6[2016.0]

2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
       ..
263   NaN
264   NaN
265   NaN
266   NaN
267   NaN
Name: 2016.0, Length: 266, dtype: float64

In [66]:
f6.rename({2016.0:'_2016',2017.0:'_2017',2018.0:'_2018',2019.0:'_2019',2020.0:'_2020',2021.0:'_2021'},axis=1,inplace=True)

In [67]:
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,_2021,
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN,

In [68]:
f6.columns[-1]

''

In [69]:
f6.drop('', axis = 1, inplace = True)

In [70]:
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2012,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,_2021
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,2.80379593014382,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.94664348429988,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,39.2005157962605,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.235571260306243,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,68.5988972147604,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0761043964019097,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.145536869340233,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.554167119417581,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN

# fill values from 2016 to 2021¶

In [71]:
for i,v in enumerate(f6.columns[60:]):
    f6[v] = f6[f6.columns[60+i:64+i]].mean(axis=1)
f6

1,Country Name,Country Code,Indicator Name,Indicator Code,_1960,_1961,_1962,_1963,_1964,_1965,...,_2012,_2013,_2014,_2015,_2016,_2017,_2018,_2019,_2020,_2021
2,Aruba,ABW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,2.80379593014382,3.12291499758958,3.19332933523694,3.33076647467845,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,,,,,NaN,NaN,NaN,NaN,NaN,NaN
5,Africa Western and Central,AFW,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,6.94664348429988,6.89366790527732,7.42563871711695,7.82024821265885,NaN,NaN,NaN,NaN,NaN,NaN
6,Angola,AGO,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,39.2005157962605,41.9790652385589,46.8248945147679,46.8250716919295,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.235571260306243,0.229885057471264,0.275938189845475,0.245138094459879,NaN,NaN,NaN,NaN,NaN,NaN
264,"Yemen, Rep.",YEM,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,68.5988972147604,67.9802376191036,61.443892231232,60.1952684941795,NaN,NaN,NaN,NaN,NaN,NaN
265,South Africa,ZAF,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.0761043964019097,0.0758317798350659,0.0757603088134493,0.074168341871474,NaN,NaN,NaN,NaN,NaN,NaN
266,Zambia,ZMB,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.145536869340233,0.142857142857143,2.83697758095765,3.00617605476598,NaN,NaN,NaN,NaN,NaN,NaN
267,Zimbabwe,ZWE,Electricity production from oil sources (% of ...,EG.ELC.PETR.ZS,,,,,,,...,0.554167119417581,0.595611285266458,0.538599640933573,0.494386651560408,NaN,NaN,NaN,NaN,NaN,NaN

# save the csv file after cleaning (make sure give correct path for saving the file as per your choice)

In [ ]:
f6.to_csv('c:/oil_resources.csv', index=False)

In [104]:
f7=pd.read_json('elec_produc_renewal_resources.json')
f7.to_csv('file7.csv')
f7

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
0,Last Updated Date,2022-07-20,,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,

In [105]:
f7.drop(0,axis=0,inplace=True)
f7

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,66
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,2.220000e+08,2.330000e+08,2.800000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,

In [106]:
f7.columns=f7.iloc[0]
f7

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.013000e+03,2.014000e+03,2.015000e+03,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,2.220000e+08,2.330000e+08,2.800000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,

In [108]:
f7.drop(1,axis=0,inplace=True)

In [109]:
f7

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,2.220000e+08,2.330000e+08,2.800000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,

In [111]:
f7.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,3.669000e+09,7.687000e+09,1.092600e+10,NaN,NaN,NaN,NaN,NaN,NaN,
2,4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,2.220000e+08,2.330000e+08,2.800000e+08,NaN,NaN,NaN,NaN,NaN,NaN,
4,6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
262,264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
263,265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,3.830000e+08,2.251000e+09,4.763000e+09,NaN,NaN,NaN,NaN,NaN,NaN,
264,266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,
265,267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,NaN,NaN,NaN,NaN,NaN,...,1.660000e+08,1.440000e+08,1.290000e+08,NaN,NaN,NaN,NaN,NaN,NaN,

In [112]:
f7.fillna(0,inplace=True)

In [113]:
f7

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.669000e+09,7.687000e+09,1.092600e+10,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,2.220000e+08,2.330000e+08,2.800000e+08,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.830000e+08,2.251000e+09,4.763000e+09,0.0,0.0,0.0,0.0,0.0,0.0,
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,1.660000e+08,1.440000e+08,1.290000e+08,0.0,0.0,0.0,0.0,0.0,0.0,

In [114]:
f7.reset_index()

1,index,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,
0,2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
1,3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,3.669000e+09,7.687000e+09,1.092600e+10,0.0,0.0,0.0,0.0,0.0,0.0,
2,4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
3,5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,2.220000e+08,2.330000e+08,2.800000e+08,0.0,0.0,0.0,0.0,0.0,0.0,
4,6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
262,264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
263,265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,3.830000e+08,2.251000e+09,4.763000e+09,0.0,0.0,0.0,0.0,0.0,0.0,
264,266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
265,267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,...,1.660000e+08,1.440000e+08,1.290000e+08,0.0,0.0,0.0,0.0,0.0,0.0,

# DATA information¶

In [115]:
f7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 2 to 267
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960.0          266 non-null    float64
 5   1961.0          266 non-null    float64
 6   1962.0          266 non-null    float64
 7   1963.0          266 non-null    float64
 8   1964.0          266 non-null    float64
 9   1965.0          266 non-null    float64
 10  1966.0          266 non-null    float64
 11  1967.0          266 non-null    float64
 12  1968.0          266 non-null    float64
 13  1969.0          266 non-null    float64
 14  1970.0          266 non-null    float64
 15  1971.0          266 non-null    float64
 16  1972.0          266 non-null    float64
 17  1973.0          266 non-null    float64
 18  1974.0          266 non-null    float64
 19  1975.0          266 non-null    float64
 20  1976.0          266 non-null    float64
 21  1977.0          266 non-null    float64
 22  1978.0          266 non-null    float64
 23  1979.0          266 non-null    float64
 24  1980.0          266 non-null    float64
 25  1981.0          266 non-null    float64
 26  1982.0          266 non-null    float64
 27  1983.0          266 non-null    float64
 28  1984.0          266 non-null    float64
 29  1985.0          266 non-null    float64
 30  1986.0          266 non-null    float64
 31  1987.0          266 non-null    float64
 32  1988.0          266 non-null    float64
 33  1989.0          266 non-null    float64
 34  1990.0          266 non-null    float64
 35  1991.0          266 non-null    float64
 36  1992.0          266 non-null    float64
 37  1993.0          266 non-null    float64
 38  1994.0          266 non-null    float64
 39  1995.0          266 non-null    float64
 40  1996.0          266 non-null    float64
 41  1997.0          266 non-null    float64
 42  1998.0          266 non-null    float64
 43  1999.0          266 non-null    float64
 44  2000.0          266 non-null    float64
 45  2001.0          266 non-null    float64
 46  2002.0          266 non-null    float64
 47  2003.0          266 non-null    float64
 48  2004.0          266 non-null    float64
 49  2005.0          266 non-null    float64
 50  2006.0          266 non-null    float64
 51  2007.0          266 non-null    float64
 52  2008.0          266 non-null    float64
 53  2009.0          266 non-null    float64
 54  2010.0          266 non-null    float64
 55  2011.0          266 non-null    float64
 56  2012.0          266 non-null    float64
 57  2013.0          266 non-null    float64
 58  2014.0          266 non-null    float64
 59  2015.0          266 non-null    float64
 60  2016.0          266 non-null    float64
 61  2017.0          266 non-null    float64
 62  2018.0          266 non-null    float64
 63  2019.0          266 non-null    float64
 64  2020.0          266 non-null    float64
 65  2021.0          266 non-null    float64
 66                  266 non-null    object
dtypes: float64(62), object(5)
memory usage: 139.4+ KB

# rename all columns' name

In [117]:
for i in f7.columns[4:]:
   f7.rename({str(i):'_'+str(i)}, axis=1, inplace=True)
f7.head()

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.669000e+09,7.687000e+09,1.092600e+10,0.0,0.0,0.0,0.0,0.0,0.0,
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,2.220000e+08,2.330000e+08,2.800000e+08,0.0,0.0,0.0,0.0,0.0,0.0,
6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,

# fill values from 2016 to 2021

In [118]:
 for i,v in enumerate(f7.columns[60:]):
    f7[v] = f7[f7.columns[56+i:60+i]].mean(axis=1)
f7

1,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,_
2,Aruba,ABW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,Africa Eastern and Southern,AFE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.669000e+09,7.687000e+09,1.092600e+10,6.335000e+09,7.154250e+09,8.025562e+09,8.110203e+09,7.406254e+09,7.674067e+09,7.804022e+09
4,Afghanistan,AFG,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
5,Africa Western and Central,AFW,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,2.220000e+08,2.330000e+08,2.800000e+08,2.327500e+08,2.419375e+08,2.469219e+08,2.504023e+08,2.430029e+08,2.455662e+08,2.464733e+08
6,Angola,AGO,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,Kosovo,XKX,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
264,"Yemen, Rep.",YEM,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
265,South Africa,ZAF,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,3.830000e+08,2.251000e+09,4.763000e+09,1.932250e+09,2.332312e+09,2.819641e+09,2.961801e+09,2.511501e+09,2.656314e+09,2.737314e+09
266,Zambia,ZMB,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
267,Zimbabwe,ZWE,"Electricity production from renewable sources,...",EG.ELC.RNWX.KH,0.0,0.0,0.0,0.0,0.0,0.0,...,1.660000e+08,1.440000e+08,1.290000e+08,1.517500e+08,1.476875e+08,1.431094e+08,1.428867e+08,1.463584e+08,1.450105e+08,1.443412e+08

# save the csv file after cleaning (make sure give correct path for saving the file as per your choice)¶

In [ ]:
f7.to_csv('c:/nuclear_sources_clean.csv', index=False)